// Recidiviz - a data platform for criminal justice reform
// Copyright (C) 2021 Recidiviz, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// =============================================================================

export const incarcerationReleasesLegacyAgeBuckets = [
  {
    state_code: "US_ND",
    gender: "ALL",
    age_bucket: "ALL",
    race_or_ethnicity: "ALL",
    total_release_count: "3492",
    external_transfer_count: "346",
    sentence_completion_count: "203",
    parole_count: "680",
    probation_count: "1088",
    death_count: "1174",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "ALL",
    age_bucket: "<25",
    race_or_ethnicity: "ALL",
    total_release_count: "504",
    external_transfer_count: "170",
    sentence_completion_count: "50",
    parole_count: "98",
    probation_count: "29",
    death_count: "157",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "ALL",
    age_bucket: "25-29",
    race_or_ethnicity: "ALL",
    total_release_count: "477",
    external_transfer_count: "160",
    sentence_completion_count: "93",
    parole_count: "47",
    probation_count: "28",
    death_count: "149",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "ALL",
    age_bucket: "30-34",
    race_or_ethnicity: "ALL",
    total_release_count: "836",
    external_transfer_count: "49",
    sentence_completion_count: "163",
    parole_count: "260",
    probation_count: "83",
    death_count: "281",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "ALL",
    age_bucket: "35-39",
    race_or_ethnicity: "ALL",
    total_release_count: "1046",
    external_transfer_count: "104",
    sentence_completion_count: "326",
    parole_count: "352",
    probation_count: "204",
    death_count: "61",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "ALL",
    age_bucket: "40<",
    race_or_ethnicity: "ALL",
    total_release_count: "629",
    external_transfer_count: "123",
    sentence_completion_count: "62",
    parole_count: "212",
    probation_count: "196",
    death_count: "37",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "ALL",
    age_bucket: "ALL",
    race_or_ethnicity: "AMERICAN_INDIAN_ALASKAN_NATIVE",
    total_release_count: "1046",
    external_transfer_count: "104",
    sentence_completion_count: "352",
    parole_count: "326",
    probation_count: "61",
    death_count: "204",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "ALL",
    age_bucket: "ALL",
    race_or_ethnicity: "BLACK",
    total_release_count: "1025",
    external_transfer_count: "344",
    sentence_completion_count: "200",
    parole_count: "319",
    probation_count: "60",
    death_count: "102",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "ALL",
    age_bucket: "ALL",
    race_or_ethnicity: "HISPANIC",
    total_release_count: "372",
    external_transfer_count: "22",
    sentence_completion_count: "37",
    parole_count: "125",
    probation_count: "116",
    death_count: "72",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "ALL",
    age_bucket: "ALL",
    race_or_ethnicity: "WHITE",
    total_release_count: "605",
    external_transfer_count: "203",
    sentence_completion_count: "188",
    parole_count: "35",
    probation_count: "118",
    death_count: "60",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "ALL",
    age_bucket: "ALL",
    race_or_ethnicity: "OTHER",
    total_release_count: "445",
    external_transfer_count: "44",
    sentence_completion_count: "139",
    parole_count: "87",
    probation_count: "150",
    death_count: "26",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "MALE",
    age_bucket: "ALL",
    race_or_ethnicity: "ALL",
    total_release_count: "1906",
    external_transfer_count: "594",
    sentence_completion_count: "189",
    parole_count: "641",
    probation_count: "371",
    death_count: "111",
    metric_period_months: "36",
  },
  {
    state_code: "US_ND",
    gender: "FEMALE",
    age_bucket: "ALL",
    race_or_ethnicity: "ALL",
    total_release_count: "1586",
    external_transfer_count: "92",
    sentence_completion_count: "494",
    parole_count: "533",
    probation_count: "309",
    death_count: "157",
    metric_period_months: "36",
  },
];
