name: "Build Status"

on:
  - push
  - pull_request

jobs:
  lint-spotlight-client:
    name: Lint Spotlight Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spotlight-client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  test-spotlight-client:
    name: Test Spotlight Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spotlight-client
    env:
      REACT_APP_API_URL: http://localhost:3002
      REACT_APP_ENABLED_TENANTS: US_ND,US_PA
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install --frozen-lockfile
      - run: yarn test --coverage --forceExit --runInBand
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          flag-name: spotlight-client
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: spotlight-client/coverage/lcov.info
  lint-spotlight-api:
    name: Lint Spotlight API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spotlight-api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  test-spotlight-api:
    name: Test Spotlight API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spotlight-api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install --frozen-lockfile
      - run: yarn test --coverage --runInBand
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          flag-name: spotlight-api
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: spotlight-api/coverage/lcov.info
  finish-coveralls:
    name: Finish Coveralls
    runs-on: ubuntu-latest
    needs: [test-spotlight-client, test-spotlight-api]
    steps:
      - name: Coveralls Parallel Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
