name: nightfalldlp
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  nightfalldlp:
    name: nightfalldlp
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Repo Action
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: nightfallDLP action step
        uses: nightfallai/nightfall_dlp_action@fc69e6696c775bc5ec3b81a3f0ff74f1511f9f33 # v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIGHTFALL_API_KEY: ${{ secrets.NIGHTFALL_API_KEY }}
          EVENT_BEFORE: ${{ github.event.before }}
