name: "CI: Spotlight Client"

on: [push, pull_request]

defaults:
  run:
    working-directory: spotlight-client

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: "12.x"
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install
      - run: yarn lint
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: "12.x"
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install
      - run: yarn test --coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          base-path: spotlight-client
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: spotlight-client/coverage/lcov.info
