name: Spotlight Staging Deploy
on:
  push:
    branches:
      # TODO: should be master, not this test branch
      - ian/336-deploy
    paths:
      - "spotlight-client/**"
defaults:
  run:
    working-directory: spotlight-client

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        # in lieu of build-staging, which consumes a .env that is not available in CI,
        # we configure the build for staging here
        env:
          REACT_APP_AUTH_ENABLED: true
          REACT_APP_AUTH_ENV: development
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: yarn build
      - name: Store build artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy frontend
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCT_KEY }}
        with:
          args: deploy -P staging
