name: "CI: Spotlight Client"

on:
  push:
    paths:
      - "spotlight-client/**"
      - "*"
  pull_request:
    paths:
      - "spotlight-client/**"
      - "*"

defaults:
  run:
    working-directory: spotlight-client

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: "12.x"
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: "12.x"
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install --frozen-lockfile
      # even though watching is automatically disabled in the CI environment, coverage fails
      # unless we explicitly disable it via --watchAll; if you would like to see people argue
      # about whether this is a bug or not, go here: https://github.com/facebook/create-react-app/issues/6888
      - run: yarn test --coverage --watchAll=false
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          base-path: spotlight-client
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: spotlight-client/coverage/lcov.info
