name: "CI: Spotlight API"

on: push

defaults:
  run:
    working-directory: spotlight-api

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: "12.x"
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install
      - run: yarn lint
