name: CI Checks

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1.1.0
        with:
          node-version: "10.x"

      # https://github.com/marketplace/actions/yarn-install-cache
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint

  test-js:
    name: test JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1.1.0
        with:
          node-version: "10.x"

      # https://github.com/marketplace/actions/yarn-install-cache
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn run test
